### ISSUE TITLE
Music Understaing LLM

### ISSUE THREAD

**Issue by shansongliu** [EmulationAI/awesome-large-audio-models#3]
Our model is based on the LLaMA LLM which is capable of music question answering and music captioning. You may add it to your list too. Here is the link: https://arxiv.org/abs/2308.11276. The associated github link is here: https://github.com/crypto-code/MU-LLaMA

**Comment by shansongliu** [comment]
And here is the link of our associated self-created dataset for training our proposed model. https://huggingface.co/datasets/mu-llama/MusicQA.

**Comment by fahadshamshad** [comment]
Thanks. We have added the paper, and code.

**Comment by shansongliu** [comment]
Many thanks! But it seems that the Github link redirects to this repo https://github.com/ChristophReich1996/Cell-DETR, which is incorrect. I would greatly appreciate it if you could correct it using this link https://github.com/crypto-code/MU-LLaMA.

**Comment by fahadshamshad** [comment]
We have updated the link now.

**Comment by shansongliu** [comment]
Thanks! And thank you for your contributions to the community of audio-related LLM models!
