### ISSUE TITLE
MuseCoco in the paper

### ISSUE THREAD

**Issue by xxupiano** [EmulationAI/awesome-large-audio-models#4]
Thanks for the nice survey. 

There is a mistake in [Section 3.5](https://arxiv.org/pdf/2308.12792.pdf): "To train text-to-attribute conversion, they used a variety of MIDI datasets" ->  "To train attribute-to-music conversion, they used a variety of MIDI datasets".

**Comment by xxupiano** [comment]
And the Emogen is released https://arxiv.org/pdf/2307.01229.pdf.
We will update our paper soon.

**Comment by fahadshamshad** [comment]
We have updated the draft accordingly, and planning to upload second version in coming 2-3 days. Thanks for your interest.
