### ISSUE TITLE
The X-LLM with speech inputs. 

### ISSUE THREAD

**Issue by MingLunHan** [EmulationAI/awesome-large-audio-models#5]
Hello there! To the best of my knowledge, our X-LLM is among the pioneering efforts to explore the integration of audio information into LLM (Large Language Model). The article _X-LLM: Bootstrapping Advanced Large Language Models by Treating Multi-Modalities as Foreign Languages_ has been published on arxiv in May 7th this year. Can you add it to this repository and include it in the paper? In our paper, we investigated the simultaneous integration of audios, images, and videos into LLM. You can find the article at this link: [X-LLM: Bootstrapping Advanced Large Language Models by Treating Multi-Modalities as Foreign Languages](https://arxiv.org/abs/2305.04160), and the corresponding GitHub repository is available here: [https://github.com/phellonchen/X-LLM](https://github.com/phellonchen/X-LLM). Please let me know if there's anything else I can assist you with!

**Comment by fahadshamshad** [comment]
Please send us a pull request. We will merge it. Thanks.

**Comment by MingLunHan** [comment]
@fahadshamshad Thank you! I have sent a pull request. Please review the update!
